### ISSUE TITLE
Invite Logger Doesn't Work.

### ISSUE THREAD

**Issue by Itz-Hyperz** [KarimX32/UltraX-Package#37]
What up!

Node Version: 16 (LATEST)
DiscordJS Version: 13.1 (LATEST)
Package Version (LATEST)

here is my client, as-well as it being binded to the client.
![](https://cdn.hyperz.dev/p1nyncfp.png)

Then here is the physical event handler, which would enforce it into the handler with client.on()
![](https://cdn.hyperz.dev/9lar4t09.png)

Which it is inside of the events folder of course, as all other events work just fine.
![](https://cdn.hyperz.dev/4tib0tco.png)

There is no error within console when a user joins with an invite, and there is nothing happening on the event itself.

**Leaving me to believe the package's invite logger is just broken.**
Here is my code:
![](https://cdn.hyperz.dev/l6o11s48.png)

**Comment by Itz-Hyperz** [comment]
Did a little bit of debugging in the node module, I went ahead and console logged after each log, and it won't go above 9 in the console loggers, so it is failing to run this code:

```js
const invite = guildInvites.find(i => {
  const a = ei.get(i.code);
  if (!a) return;
  return a.uses < i.uses
});
```

Here is an image of the logger stuffs:
![](https://cdn.hyperz.dev/i521fwr0.png)

If you could figure out a fix, I'll keep looking in the mean time.

https://discordjs.guide/additional-info/changes-in-v13.html#guild

**Comment by Itz-Hyperz** [comment]
OKAY, did a little bit more digging.

Found out that this code:
```js
a.uses < i.uses
```

when returning from trying to find in the invite, it returns `undefined`

I will search for a solution

**Comment by Itz-Hyperz** [comment]
#38 I have fixed it here

**Comment by Itz-Hyperz** [comment]
now it all works properly and as advertised!
![](https://cdn.hyperz.dev/28jetxaj.png)

**Comment by BIntelligent** [comment]
Oh sorry for inconvenience but thanks for finding the issue
