### ISSUE TITLE
Invites Broken

### ISSUE THREAD

**Issue by Itz-Hyperz** [KarimX32/UltraX-Package#39]
Update, the pull request I made to fix invites ( #38 ) works about 50% of the way, it doesn't update invites until the bot is restarted, and is stuck on the same invite each time, unable to find a workaround, so this is unfortunately still broken.

**Comment by reinacchi** [comment]
Can you elaborate on the issue so I can take a quick through on the code?

**Comment by Itz-Hyperz** [comment]
it fetches invites, but when a user joins, it isn't filtering what user invited them. It just goes to the "top" invite, which is in the find statement, as it isn't being filtered by anything.

**Comment by Itz-Hyperz** [comment]
**REFERENCE:** https://support.discord.com/hc/en-us/community/posts/4407889835287-INVITE-CODE-WHEN-A-USER-JOINS-

**Comment by RaZeSloth** [comment]
Has this been resolved or not?

**Comment by reinacchi** [comment]
I don't see any PR linked to this, no
