### ISSUE TITLE
WelcomeImage.js unsupported image type

### ISSUE THREAD

**Issue by ItsFranklinMyDudes** [KarimX32/UltraX-Package#54]
**Describe the bug**  

when running the the even, it says ` Unsupported image type`, i tryed changing it to jpg but nothing

**Error**  

[A screenshot or the text block of the error if there is one.](https://ibb.co/w6gv9TG)

**To Reproduce**  

update the package to v14 or something

**Expected behavior**  

no sure

**Screenshots**  

already did

**Additional info**

nothing

**Comment by KarimX32** [comment]
> **Describe the bug**
> 
> when running the the even, it says ` Unsupported image type`, i tryed changing it to jpg but nothing
> 
> **Error**
> 
> [A screenshot or the text block of the error if there is one.](https://ibb.co/w6gv9TG)
> 
> **To Reproduce**
> 
> update the package to v14 or something
> 
> **Expected behavior**
> 
> no sure
> 
> **Screenshots**
> 
> already did
> 
> **Additional info**
> 
> nothing

Ill need to see your code please.

**Comment by ItsFranklinMyDudes** [comment]
> Ill need to see your code please.

sorry for the long wait, i forgot about this
```js
/*
  const bg = 'https://imgur.com/okIR1iY.png';
        const avatar = member.user.displayAvatarURL({ format: "png" });
        const title = "Welcome";
        const subtitle = member.user.tag;
        const footer = `You're the ${member.guild.memberCount}th member`;
        const color = '#ffffff';
        const options = {
            font: "sans-serif",
            attachmentName: `welcome-${member.username}`,
            title_fontSize: 80,
            subtitle_fontSize: 50,
            footer_fontSize: 30
        };
        const image = await welcomeImage(bg, avatar, title, subtitle, footer, color, options);
        */
        const welcome = new EmbedBuilder()
            .setTitle('New Member Joined')
            .setDescription(`
                Welcome ${member} to Franklin's Brain, We hope you enjoy is here :)
                Go get some Roles to spice it up a little
            `)
            .setColor('Orange')
            .setTimestamp()
        //.setImage(image)
```

**Comment by KarimX32** [comment]
that issue isnt coming from our package apparently, some people had some issues with something similar, its about canvas with discord.js or something like that, I'm not entirely sure, but I guarantee its not coming from the package, in case this never worked we will be making it as an API endpoint so you can fetch it without having to install canvas and deal with it.

**Comment by ItsFranklinMyDudes** [comment]
> that issue isnt coming from our package apparently, some people had some issues with something similar, its about canvas with discord.js or something like that, I'm not entirely sure, but I guarantee its not coming from the package, in case this never worked we will be making it as an API endpoint so you can fetch it without having to install canvas and deal with it.

oh ok, will i think i went throw the files of canvas and couldn't find anything, i'll have another look, if not we'll idk

**Comment by KarimX32** [comment]
Hello Franklin, found out its a discord.js error

here is a fix
https://stackoverflow.com/questions/73489458/discord-node-js-canvas-error-unsupported-image-type

**Comment by ItsFranklinMyDudes** [comment]
> Hello Franklin, found out its a discord.js error
> 
> 
> 
> here is a fix
> 
> https://stackoverflow.com/questions/73489458/discord-node-js-canvas-error-unsupported-image-type

oh cool thx, i'll have a look at it
