### ISSUE TITLE
I have a issuse with button paginator

### ISSUE THREAD

**Issue by straledev** [KarimX32/UltraX-Package#7]
I just have a problem with button paginator when i put a regular emoji name, id, and animated, bot shows a error on console and command doesn't works. On attachments you can see error.

![Discord_ZYn0FEVKGo](https://user-images.githubusercontent.com/74136297/124326639-08d24d00-db87-11eb-89be-d0c44544a0a9.png)

![Code_6rySnu8pby](https://user-images.githubusercontent.com/74136297/124326687-21426780-db87-11eb-88e5-e6a31332c886.png)

**Comment by reinacchi** [comment]
> I just have a problem with button paginator when i put a regular emoji name, id, and animated, bot shows a error on console and command doesn't works. On attachments you can see error.
> 
> ![Discord_ZYn0FEVKGo](https://user-images.githubusercontent.com/74136297/124326639-08d24d00-db87-11eb-89be-d0c44544a0a9.png)
> 
> ![Code_6rySnu8pby](https://user-images.githubusercontent.com/74136297/124326687-21426780-db87-11eb-88e5-e6a31332c886.png)

Could you try removing the `id` param?
